resources:
- repo: self

queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: Win32DotNet.sln
    arguments: '/v:d /p:Configuration=Release'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: src/Win32DotNet/Win32DotNet.csproj
    buildProperties: 'Configuration=Release;BuildNumber=$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Win32DotNet'
  inputs:
    artifactName: 'Win32DotNet'


